version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartuser54
      POSTGRES_DB: smartdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://smartuser:smartuser54@localhost:5432/smartdata
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data: