FROM python:3.12-slim


#Working directory
WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

#Install python dependencies
RUN pip install --no-cache-dir -r requirements.txt

#copy rest of the application
COPY . .

# Create uploads directories
RUN mkdir -p uploads/raw_uploads uploads/processed

# Expose port
EXPOSE 8000

# Run the application with uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]