"""add analysis_report and analyzed_at to datasets

Revision ID: 000eb005430a
Revises: e226f0096f37
Create Date: 2026-03-15 18:12:46.959421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000eb005430a'
down_revision: Union[str, Sequence[str], None] = 'e226f0096f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('analysis_report', sa.JSON(), nullable=True))
    op.add_column('datasets', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'analyzed_at')
    op.drop_column('datasets', 'analysis_report')
    # ### end Alembic commands ###
