"""empty message

Revision ID: 3e5ebd625ef0
Revises: dfc4e5ab35eb
Create Date: 2026-03-14 12:23:45.475957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5ebd625ef0'
down_revision: Union[str, Sequence[str], None] = 'dfc4e5ab35eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('col_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'col_count')
    # ### end Alembic commands ###
